# Generated by Django 4.1.1 on 2022-09-28 13:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chess_instructor_profile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
