# Generated by Django 4.1.1 on 2022-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_chess_instructor_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='chess_actual_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='chess_actual_rating_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='chess_top_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='chess_top_rating_date',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='chess_top_rating_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='fide_com',
            field=models.URLField(default=''),
        ),
    ]
