# Generated by Django 4.1.1 on 2022-09-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_chess_instructor_profile_accepts_new_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='chess_instructor_profile',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
