# Generated by Django 4.1.1 on 2022-10-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_chess_instructor_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chess_Instructor_Profile',
        ),
    ]
