# Generated by Django 4.1.1 on 2022-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=63)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uri', models.CharField(blank=True, default='', max_length=63)),
            ],
        ),
    ]
