# Generated by Django 4.1.1 on 2022-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videovimeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='status',
            field=models.CharField(blank=True, default='processing', max_length=63),
        ),
    ]
