# Generated by Django 4.1.1 on 2022-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videovimeo', '0002_uploadvideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='link_lokal',
            field=models.CharField(default='', max_length=63),
        ),
    ]
