# Generated by Django 4.1.1 on 2022-10-03 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videovimeo', '0003_uploadvideo_link_lokal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='link_lokal',
            new_name='link_vimeo',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
