# Generated by Django 4.1.1 on 2022-09-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0002_profile_owner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_owner',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
