# Generated by Django 4.1.1 on 2022-09-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0003_alter_profile_owner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
