# Generated by Django 4.1.1 on 2022-09-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0004_profile_owner_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_owner',
            name='desc',
        ),
    ]
