# Generated by Django 4.1.1 on 2022-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0005_remove_profile_owner_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='socials',
            field=models.JSONField(default=dict),
        ),
    ]
