# Generated by Django 4.1.1 on 2022-09-29 11:39

from django.db import migrations, models
import profile_owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0006_profile_owner_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_owner',
            name='link',
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='accepts_new_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='chess_profile',
            field=models.JSONField(default=profile_owner.models.default_chess_profile),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='hidden_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='languages',
            field=models.CharField(blank=True, default='eng', max_length=16),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=65),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='profile_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='profile_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='socials',
            field=models.JSONField(default=profile_owner.models.default_socials),
        ),
    ]
