# Generated by Django 4.1.1 on 2022-09-29 11:44

from django.db import migrations, models
import profile_owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0007_remove_profile_owner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='checkers_profile',
            field=models.JSONField(default=profile_owner.models.default_checkers_profile),
        ),
    ]
