# Generated by Django 4.1.1 on 2022-09-29 13:18

from django.db import migrations, models
import profile_owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0008_profile_owner_checkers_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='languages_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='accepts_new_students',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='checkers_profile',
            field=models.JSONField(blank=True, default=profile_owner.models.default_checkers_profile),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='chess_profile',
            field=models.JSONField(blank=True, default=profile_owner.models.default_chess_profile),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='hidden_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='profile_is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='socials',
            field=models.JSONField(blank=True, default=profile_owner.models.default_socials),
        ),
    ]
