# Generated by Django 4.1.1 on 2022-09-29 13:59

from django.db import migrations, models
import profile_owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0010_languages_remove_profile_owner_languages_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=profile_owner.models.nameFile)),
            ],
        ),
    ]
