# Generated by Django 4.1.1 on 2022-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0013_alter_profile_owner_profile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='is_instructor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
