# Generated by Django 4.1.1 on 2022-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0014_profile_owner_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='country',
            field=models.CharField(blank=True, default='pl', max_length=5),
        ),
    ]
