# Generated by Django 4.1.1 on 2022-10-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0016_profiletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='profileType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profile_owner.profiletype'),
        ),
    ]
