# Generated by Django 4.1.1 on 2022-10-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0017_profile_owner_profiletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_owner',
            name='profile_type',
        ),
    ]
