# Generated by Django 4.1.1 on 2022-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0018_remove_profile_owner_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_owner',
            name='TeachingExperience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile_owner',
            name='successes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile_owner',
            name='checkers_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
