# Generated by Django 4.1.1 on 2022-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_owner', '0019_profile_owner_teachingexperience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_owner',
            old_name='TeachingExperience',
            new_name='teachingExperience',
        ),
    ]
